Dev
Arm-U/cipher pull request #1
Opened 2020-04-17 22:40 UTC by Arm-U

2020-04-19 12:39 UTC, pkositsyn requested changes

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +    if args.code == "encode" or args.code == "decode" or args.code == "hack":
args.code in ('encode', ... )

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +def fileread(args: argparse.Namespace) -> list:
typing.List[str]

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +                sys.exit()
Вынеси в функцию или контекстный менеджер

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +                    raise Exception()
Лучше просто open и ловить все что пришло, не надо бросать обычный Exception

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +    infile.close()
Вот от этого нужен контекстный менеджер

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +    def encode(key: int, itter: list) -> list:
положи ключ в класс и не делай staticmethod

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +    def decode(key: int, itter: list) -> list:
можно вызвать encode с -key

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +    def decode(key: str, itter: list) -> list:
можно внутри encode вызывать

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +                onlyAlpha[item] = myDict[item] / alphaNums
надо делить не на alphaNums а на сумму значений словаря. И проверить, что это не 0

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +                raise Exception()
Убери, дальше все равно бросит исключение если не сможе тоткрыть

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +                measure += abs(myDict[item] - itterDict[item] / alphaNums)
аналогично про alphaNums

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +            except ValueError:
Оберни только приведение к инту

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +            dec_text = Vigenre.encode(args.key, text)
Он же Vigener

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +def Code(args: argparse.Namespace) -> None:
с маленькой буквы названия функций

2020-04-19 12:39 UTC, pkositsyn commented on cipher.py
> +args = Parser()
Сделай точку входа `if __name__ == '__main__': main()`
def main():
...

2020-04-19 14:16 UTC, Arm-U commented on cipher.py
> +args = Parser()
Исправил

2020-04-19 14:16 UTC, Arm-U commented on cipher.py
> +def Code(args: argparse.Namespace) -> None:
Исправил

2020-04-19 14:18 UTC, Arm-U commented on cipher.py
> +            dec_text = Vigenre.encode(args.key, text)
Оказывается Vigenere. Исправил

2020-04-19 14:26 UTC, Arm-U commented on cipher.py
> +            except ValueError:
Сделано

2020-04-19 14:27 UTC, Arm-U commented on cipher.py
> +    def decode(key: int, itter: list) -> list:
Нужно ли decode заменить или можно оставить так как было ?

2020-04-19 14:30 UTC, Arm-U commented on cipher.py
> +                raise Exception()
Убрал

2020-04-19 14:31 UTC, Arm-U commented on cipher.py
> +    def decode(key: str, itter: list) -> list:
Нужно ли decode заменить или можно оставить так как было ?

2020-04-19 14:43 UTC, Arm-U commented on cipher.py
> +    if args.code == "encode" or args.code == "decode" or args.code == "hack":
Сделано

2020-04-19 14:43 UTC, Arm-U commented on cipher.py
> +def fileread(args: argparse.Namespace) -> list:
Сделано

2020-04-19 15:40 UTC, Arm-U commented on cipher.py
> +    def encode(key: int, itter: list) -> list:
Я сделал staticmethod, чтобы не писать self

2020-04-19 16:00 UTC, Arm-U commented on cipher.py
> +                    raise Exception()
Пофиксил

2020-04-19 16:00 UTC, Arm-U commented on cipher.py
> +    infile.close()
Ничего не понял. Можно подробней ?

2020-04-19 16:02 UTC, Arm-U commented on cipher.py
> +                sys.exit()
Когда делаю контекстный менеджер он после окончания with закрывает файл. А я дальше с ним работаю

2020-04-19 16:22 UTC, Arm-U commented on cipher.py
> +                onlyAlpha[item] = myDict[item] / alphaNums
Исправил

2020-04-19 16:22 UTC, Arm-U commented on cipher.py
> +                measure += abs(myDict[item] - itterDict[item] / alphaNums)
Исправил

2020-04-25 15:29 UTC, pkositsyn requested changes

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +def textprint(output_file: str, text: list) -> None:
не list а typing.List[str]

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +    parser.add_argument("code", help="What to do")
Сделай, пожалуйста, subparser, чтобы для каждого действия были свои аргументы

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +            text.append(symbols)
это можно заменить на text = list(infile.read())

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +    infile.close()
Когда сделаешь subparser тебе достаточно будет при любом действии читать либо из stdin, либо из файла. Уберется разветвление, и лучше будет сделать свой контекстный менеджер, в который можно обернуть весь логический код внутри. Просто при исключении ты не закроешь файл, и он останется открытым до конца работы программы. Так не надо делать

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +                raise Exception()
Я вроде говорил это убрать. Тем более тебе нужно создать файл, если его нет. Поэтому здесь не надо  завершаться с неудачей

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +        outfile.write(letter)
Можно просто записать весь текст, зачем по букве, это же долго

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +    @staticmethod
Почему надо бы сложить ключ в класс. Ты когда работаешь с одним объектом, скорее всего то одна сессия, где нужно кодировать текст, не меняя ключ. Поэтому нет смысла каждый раз передавать его. Лучше один раз положить и работать. А в self нет ничего плохого, пусть будет

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +    def decode(key: int, itter: typing.List[str]) -> typing.List[str]:
Сделай через encode с -key

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +                    (string.ascii_lowercase.find(chr) + 26 -
Не надо 26 прибавлять нигде, в питоне отрицательные числа по модулю неотрицательные

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +                onlyAlpha[item] = myDict[item] / alphaNums
Не вижу, чтобы исправил. Это все еще количество

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +                raise Exception()
не вижу

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +                measure += abs(myDict[item] - itterDict[item] / alphaNums)
неа

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +            textprint(args.output_file, dec_text)
Эту строчку дублируешь везде. Можно написать 1 раз после всех ифов

2020-04-25 15:29 UTC, pkositsyn commented on cipher.py
> +def Parser() -> argparse.Namespace:
функция со строчных букв

2020-04-25 15:31 UTC, pkositsyn commented on cipher.py
> +    def decode(key: str, itter: list) -> list:
Надо просто внутри decode вызвать encode

2020-04-26 16:57 UTC, Arm-U commented on cipher.py
> +    infile.close()
Сделано

2020-04-26 16:57 UTC, Arm-U commented on cipher.py
> +                measure += abs(myDict[item] - itterDict[item] / alphaNums)
Вроде исправил

2020-04-26 16:58 UTC, Arm-U commented on cipher.py
> +    def decode(key: str, itter: list) -> list:
Заменил

2020-04-26 16:59 UTC, Arm-U commented on cipher.py
> +                onlyAlpha[item] = myDict[item] / alphaNums
Вроде исправил

2020-04-26 17:00 UTC, Arm-U commented on cipher.py
> +                raise Exception()
Заменил

2020-04-26 17:00 UTC, Arm-U commented on cipher.py
> +    parser.add_argument("code", help="What to do")
Сделано

2020-04-26 17:00 UTC, Arm-U commented on cipher.py
> +def textprint(output_file: str, text: list) -> None:
Сделано

2020-04-26 17:01 UTC, Arm-U commented on cipher.py
> +            text.append(symbols)
Заменил

2020-04-26 17:01 UTC, Arm-U commented on cipher.py
> +                raise Exception()
Убрал

2020-04-26 17:01 UTC, Arm-U commented on cipher.py
> +        outfile.write(letter)
Заменил

2020-04-26 17:01 UTC, Arm-U commented on cipher.py
> +    def decode(key: int, itter: typing.List[str]) -> typing.List[str]:
Сделано

2020-04-26 17:02 UTC, Arm-U commented on cipher.py
> +                    (string.ascii_lowercase.find(chr) + 26 -
Изменил

2020-04-26 17:06 UTC, Arm-U commented on cipher.py
> +def Parser() -> argparse.Namespace:
Изменил

2020-05-04 19:54 UTC, pkositsyn requested changes

2020-05-04 19:54 UTC, pkositsyn commented on cipher.py
> +    yield stream
тут нужен try finally, как я показывал. Всегда при создании КС

2020-05-04 19:54 UTC, pkositsyn commented on cipher.py
> +        return Caesar(self.key).encode(itter)
self.encode И верни потом ключ на место

2020-05-04 19:54 UTC, pkositsyn commented on cipher.py
> +        textprint(args.output_file, FreqAnalysis(args.model_file).hack(text))
Из серьезного прошу только эту часть исправить. train и hack оставь как есть, а с остальными сначала создай класс Caesar, Vigenere, Vernam в зависимости от того, что нужно, а затем у этого объекта вызови encode или decode по надобности. То есть всего 5 ифов

2020-05-04 19:54 UTC, pkositsyn commented on cipher.py
> +        for i in range(5):
Что за магическая константа, обработай

2020-05-05 16:44 UTC, Arm-U commented on cipher.py
> +        for i in range(5):
Это возвращаемое значение. Снизу я его меняю

2020-05-05 17:14 UTC, Arm-U commented on cipher.py
> +    yield stream
Если так сделать, то я не смогу контролировать FileNotFoundError.

2020-05-08 18:50 UTC, pkositsyn commented on cipher.py
> +    yield stream
Ты это будешь контроллировать вне менеджера. try + finally не глушит исключение. То есть если оно вылетает внутри, то в данном месте выполнится finally, а исключение полетит дальше

2020-05-08 18:53 UTC, pkositsyn commented on cipher.py
> +        return Caesar(self.key).encode(itter)
Не исправил. должно быть
`self.key *= -1`
`result = self.encode(itter)`
`self.key *= -1`
`return result`

2020-05-08 18:53 UTC, pkositsyn commented on cipher.py
> +        textprint(args.output_file, FreqAnalysis(args.model_file).hack(text))
Ok, молодец

2020-05-08 18:54 UTC, pkositsyn commented on cipher.py
> +        for i in range(5):
Вынеси в константу, пожалуйста

2020-05-08 18:54 UTC, pkositsyn commented on cipher.py
> +        for i in range(5):
Или по крайней мере len(...)

2020-05-08 18:55 UTC, pkositsyn requested changes
Доделай совсем чуть-чуть. С классами ты очень правильно понял идею, молодец. Поставлю тебе максимальные доп 2 балла за проделанную работу

2020-05-09 05:17 UTC, Arm-U commented on cipher.py
> +    yield stream
Сделано

2020-05-09 05:17 UTC, Arm-U commented on cipher.py
> +        return Caesar(self.key).encode(itter)
Сделано

2020-05-09 05:18 UTC, Arm-U commented on cipher.py
> +        for i in range(5):
Сделано

2020-05-11 08:41 UTC, pkositsyn approved these changes
OK

2020-05-12 06:47 UTC, merged